#!/bin/bash

# Update Avahi for pan0
sudo sed -i 's/#domain-name=local/domain-name=local/' /etc/avahi/avahi-daemon.conf
sudo sed -i 's/publish-hinfo=no/publish-hinfo=yes/' /etc/avahi/avahi-daemon.conf
sudo sed -i 's/publish-workstation=no/publish-workstation=yes/' /etc/avahi/avahi-daemon.conf
sudo sed -i '/allow-interfaces/ {/pan0/! s/$/, pan0/ }' /etc/avahi/avahi-daemon.conf
if grep -G "^#allow-interfaces" /etc/avahi/avahi-daemon.conf > /dev/null; then sudo sed -i 's/#allow-interfaces/allow-interfaces/' /etc/avahi/avahi-daemon.conf; fi